services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sistemaaluguel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

    volumes:
      - ./data:/var/opt/postgres/data
      - ./log:/var/opt/postgres/log